# Generated by Django 5.1.5 on 2025-03-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAMATAMA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='models_friend_invites',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='models_friend_invites',
            unique_together={('player1', 'player2')},
        ),
    ]
