# Generated by Django 5.1.5 on 2025-03-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAMATAMA', '0002_models_friend_invites_is_accepted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='models_global_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=15)),
                ('message_text', models.CharField(max_length=141)),
                ('message_date', models.DateField()),
            ],
        ),
    ]
