# Generated by Django 5.1.5 on 2025-04-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAMATAMA', '0003_models_global_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bg_color',
            field=models.CharField(default='#C1CFA1;', max_length=15),
            preserve_default=False,
        ),
    ]
